language: node_js
node_js:
    - "stable"
    - "4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "sleep 3" # give xvfb some time to start
before_script: 
    - npm install -g gulp
notifications:
    email:
        on_success: change
        on_failure: change